version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: alumni_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alumni_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: alumni_backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/alumni_db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: alumni_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
