# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; the default value is %%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library.
# timezone = 

# max length of characters to span over multiple lines in the generated script
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without a source .py file to be detected as revisions in the versions/ directory
# sourceless = false

# version location specification; This defaults to migrations/versions.  When using multiple version
# directories, platforms, etc., see the documentation for details.
# version_locations = %(here)s/bar:%(here)s/bat:migrations/versions

# version_path_separator = :

# set to 'true' to search source files recursively
# recursive_version_search = false

# the output encoding used when revision files are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = postgresql://postgres:password@localhost:5432/alumni_db


[post_write_hooks]
# post_write_hooks allows scripts to be run after generating a revision file.
# see the documentation for details.

[logging]
# logging configuration
# see the documentation for details.
